language: python
python:
    - "2.7"
before_install:
    "sudo apt-get upgrade -qq"
    "sudo apt-get install -y hdf5"
install:
    - "pip install -r requirements.txt --use-mirrors"
    # - "pip install coverage"
    # - "pip install coveralls"
script: 
    - "py.test -s ABXpy/test"
# after_success:
#     coveralls
