language: python
python:
    - "2.7"
before_install:
    - "sudo apt-get update -qq"
    - "sudo apt-get install -y libhdf5-serial-dev"
    - "sudo apt-get install -y libblas-dev"
install:
    - "pip install cython"
    - "pip install -r requirements.txt"
    # - "pip install coverage"
    # - "pip install coveralls"
script: 
    - "py.test -s ABXpy/test"
# after_success:
#     coveralls
