language: python
python:
    - "2.7"
install:
    - "sudo apt-get install hdf5"
    - "pip install -r requirements.txt --use-mirrors"
    # - "pip install coverage"
    # - "pip install coveralls"
script: 
    - "py.test -s ABXpy/test"
# after_success:
#     coveralls
