language: python
python:
    - "2.7"
# before_install:
#     - "sudo apt-get update -qq"
#     - "sudo apt-get install -y libhdf5-serial-dev"
#     - "sudo apt-get install -y libblas-dev liblapack-dev"
# install:
#     - "pip install cython"
#     - "pip install -r requirements.txt"
#     # - "pip install coverage"
#     # - "pip install coveralls"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - sudo apt-get install -qq python-numpy python-scipy
# Install packages
install:
  - conda install --yes python=2.7 numpy scipy h5py pandas pytest
  - pip search h5features
  - pip install -r h5features
  # Coverage packages are on my binstar channel
  - python setup.py install

script: 
    - "py.test -s ABXpy/test"
# after_success:
#     coveralls
