notifications:
  email: false

# no need of git history
git:
  depth: 1

# test only the master branch
branches:
  only:
    - master

install:
  # setup anaconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # useful for debugging any issues with conda
  - conda info -a
  # install ABXpy environment
  - conda env create -n test-environment -f environment.yml
  - conda activate test-environment
  - pip install codecov
  # install ABXpy
  - python setup.py build
  - python setup.py install

script:
  - pytest

after_success:
  - codecov
