name: ABXpy
dependencies:
  - cython
  - h5py
  - numpy
  - numpydoc
  - mock
  - pip
  - python=2.7
  - pandas
  - pytables
  - pytest
  - pytest-cov
  - pytest-runner
  - scipy
  - setuptools
  - pip:
      - git+https://github.com/bootphon/h5features.git
